C_1.2
Nikolay38744/SD pull request #1
Opened 2023-12-14 14:29 UTC by Constantine7266

Запрос на извлечение для Nikolay на HP
С минимальным использование GitHub

2023-12-15 10:47 UTC, Nikolay38744 commented
Запрос прошел

2023-12-15 12:45 UTC, Constantine7266 commented
Хорошо отлично

2023-12-15 14:09 UTC, Nikolay38744 reviewed
Одобряю объединение этих изменений

2023-12-15 14:17 UTC, Nikolay38744 approved these changes
Выбираем проверку Approve # утвердить

2023-12-15 15:27 UTC, Nikolay38744 approved these changes
Адобряю

2023-12-15 15:57 UTC, Nikolay38744 reviewed
Одобряю объединение этих изменений

2023-12-15 16:00 UTC, Nikolay38744 submitted a review, later dismissed
Выбираем проверку Approve # утвердить

2023-12-16 05:46 UTC, Nikolay38744 reviewed
Одобряю объединение этих изменений

2023-12-16 05:49 UTC, Nikolay38744 approved these changes
Выбираем проверку Approve # утвердить

2023-12-16 06:05 UTC, Nikolay38744 approved these changes
Выбираем прворку Approve # утвердить

2023-12-16 14:19 UTC, Nikolay38744 reviewed
Проверка

2023-12-16 14:23 UTC, Nikolay38744 reviewed
Проверка

2023-12-16 14:46 UTC, Nikolay38744 approved these changes
потверждено

2023-12-16 15:40 UTC, Nikolay38744 requested changes
Выбираем проверку Request Changes # запрос изменений

2023-12-17 06:37 UTC, Nikolay38744 approved these changes
Все правельно

2023-12-17 08:03 UTC, Nikolay38744 commented on _1/_1.1.py
> +""" Отлично ! """
Добавляем комментарий коду

2023-12-17 09:10 UTC, Nikolay38744 commented on _1/_1.1.py
> +""" Отлично ! """
Добавляем комментарий коду

2023-12-17 11:42 UTC, Nikolay38744 reviewed
ДОБАВИЛ КОММЕНТАРИЙ

2023-12-17 12:15 UTC, Nikolay38744 commented on _1/_1.1.py
> +""" Отлично ! """
```suggestion
Хорошо
```

2023-12-17 12:56 UTC, Nikolay38744 commented on _1/_1.1.py
> +""" Отлично ! """
```suggestion
""" Хорошо """
```

2023-12-17 13:46 UTC, Nikolay38744 commented on _1/_1.1.py
> +""" Отлично ! """
```suggestion
""" Хорошо """
```

2023-12-17 14:36 UTC, merged